In [6]:
# Question 1

In [7]:
import pandas as pd
import numpy as np
import os

In [8]:
# define path
path = r'/Users/amykillin/Desktop/Mark Career Foundry Data/Data Immersion/Topic 4/Instacart Basket Analysis'

In [9]:
# import dataframe
ords_prods_merge = pd.read_pickle(os.path.join(path, '2 Data', 'Prepared Data', 'df_complete_orders_products_combined_4.7.pkl'))

In [10]:
# Question 2

In [16]:
#Find mean values for the order_number comumn

ords_prods_merge.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                15.457838
2                17.277920
3                17.170395
4                17.811403
5                15.215751
6                16.439806
7                17.225802
8                15.340650
9                15.895474
10               20.197148
11               16.170638
12               15.887671
13               16.583536
14               16.773669
15               16.165037
16               17.665606
17               15.694469
18               19.310397
19               17.177343
20               16.473447
21               22.902379

In [17]:
# Question 3

The tutorial mean was different because it was analysing for a smaller subset of the overall dataframe and also only showed results for a limited number of department-id, as opposed to the whole dataframe where we see all the department_id

In [18]:
#try to run the same command with the mean function

ords_prods_merge.groupby('department_id')['order_number'].mean()

department_id
1     15.457838
2     17.277920
3     17.170395
4     17.811403
5     15.215751
6     16.439806
7     17.225802
8     15.340650
9     15.895474
10    20.197148
11    16.170638
12    15.887671
13    16.583536
14    16.773669
15    16.165037
16    17.665606
17    15.694469
18    19.310397
19    17.177343
20    16.473447
21    22.902379
Name: order_number, dtype: float64

In [24]:
#Aggregate using multiple columns

ords_prods_merge.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
1                15.457838   1  99
2                17.277920   1  99
3                17.170395   1  99
4                17.811403   1  99
5                15.215751   1  99
6                16.439806   1  99
7                17.225802   1  99
8                15.340650   1  99
9                15.895474   1  99
10               20.197148   1  99
11               16.170638   1  99
12               15.887671   1  99
13               16.583536   1  99
14               16.773669   1  99
15               16.165037   1  99
16               17.665606   1  99
17               15.694469   1  99
18               19.310397   1  99
19               17.177343   1  99
20               16.473447   1  99
21               22.902379   1  99

In [25]:
ords_prods_merge.head()
#days_since_prior_order mix of strings and int, will make all int

,Unnamed: 0_x,product_id,product_name,aisle_id,department_id,prices,Unnamed: 0_y,order_id,user_id,eval_set,...,order_dow,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day
0,0,1,Chocolate Sandwich Cookies,61,19,5.8,1987,3139998,138,prior,...,6,11,3.0,5,0,both,Mid-range product,Regularly busy,Regular days,Most orders
1,0,1,Chocolate Sandwich Cookies,61,19,5.8,1989,1977647,138,prior,...,6,17,20.0,1,1,both,Mid-range product,Regularly busy,Regular days,Average orders
2,0,1,Chocolate Sandwich Cookies,61,19,5.8,11433,389851,709,prior,...,0,21,6.0,20,0,both,Mid-range product,Busiest day,Busiest days,Average orders
3,0,1,Chocolate Sandwich Cookies,61,19,5.8,12198,652770,764,prior,...,3,13,21.0,10,0,both,Mid-range product,Regularly busy,Slowest days,Most orders
4,0,1,Chocolate Sandwich Cookies,61,19,5.8,12200,1813452,764,prior,...,4,17,9.0,11,1,both,Mid-range product,Least busy,Slowest days,Average orders

In [26]:
#Convert 'days_since_prior_order' to int
#After a few attempts, I decided to replace '1st Order' to '360' since > 20 days means 'Non-frequent customer' which they would be if it's their first order. Not a good long term solution, but will fix the issue for now.

ords_prods_merge['days_since_prior_order'] = ords_prods_merge['days_since_prior_order'].replace('1st order','21.0')

In [27]:
ords_prods_merge.head(20)
# Values are now all int, so this will fix the issue I was having previously

,Unnamed: 0_x,product_id,product_name,aisle_id,department_id,prices,Unnamed: 0_y,order_id,user_id,eval_set,...,order_dow,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day
0,0,1,Chocolate Sandwich Cookies,61,19,5.8,1987,3139998,138,prior,...,6,11,3.0,5,0,both,Mid-range product,Regularly busy,Regular days,Most orders
1,0,1,Chocolate Sandwich Cookies,61,19,5.8,1989,1977647,138,prior,...,6,17,20.0,1,1,both,Mid-range product,Regularly busy,Regular days,Average orders
2,0,1,Chocolate Sandwich Cookies,61,19,5.8,11433,389851,709,prior,...,0,21,6.0,20,0,both,Mid-range product,Busiest day,Busiest days,Average orders
3,0,1,Chocolate Sandwich Cookies,61,19,5.8,12198,652770,764,prior,...,3,13,21.0,10,0,both,Mid-range product,Regularly busy,Slowest days,Most orders
4,0,1,Chocolate Sandwich Cookies,61,19,5.8,12200,1813452,764,prior,...,4,17,9.0,11,1,both,Mid-range product,Least busy,Slowest days,Average orders
5,0,1,Chocolate Sandwich Cookies,61,19,5.8,12372,1701441,777,prior,...,1,7,26.0,7,0,both,Mid-range product,Regularly busy,Busiest days,Average orders
6,0,1,Chocolate Sandwich Cookies,61,19,5.8,13096,1871483,825,prior,...,2,14,30.0,2,0,both,Mid-range product,Regularly busy,Regular days,Most orders
7,0,1,Chocolate Sandwich Cookies,61,19,5.8,14603,1290456,910,prior,...,3,10,30.0,1,0,both,Mid-range product,Regularly busy,Slowest days,Most orders
8,0,1,Chocolate Sandwich Cookies,61,19,5.8,17065,369558,1052,prior,...,1,20,19.0,1,0,both,Mid-range product,Regularly busy,Busiest days,Average orders
9,0,1,Chocolate Sandwich Cookies,61,19,5.8,17070,589712,1052,prior,...,1,12,15.0,2,1,both,Mid-range product,Regularly busy,Busiest days,Most orders
10,0,1,Chocolate Sandwich Cookies,61,19,5.8,22082,1798115,1379,prior,...,5,11,21.0,1,0,both,Mid-range product,Regularly busy,Regular days,Most orders
11,0,1,Chocolate Sandwich Cookies,61,19,5.8,23713,497193,1480,prior,...,3,13,7.0,1,0,both,Mid-range product,Regularly busy,Slowest days,Most orders
12,0,1,Chocolate Sandwich Cookies,61,19,5.8,23715,1727826,1480,prior,...,4,13,7.0,3,1,both,Mid-range product,Least busy,Slowest days,Most orders
13,0,1,Chocolate Sandwich Cookies,61,19,5.8,23716,2694698,1480,prior,...,2,12,12.0,4,1,both,Mid-range product,Regularly busy,Regular days,Most orders
14,0,1,Chocolate Sandwich Cookies,61,19,5.8,23937,3171753,1494,prior,...,3,10,2.0,8,0,both,Mid-range product,Regularly busy,Slowest days,Most orders
15,0,1,Chocolate Sandwich Cookies,61,19,5.8,23938,186761,1494,prior,...,2,8,6.0,18,1,both,Mid-range product,Regularly busy,Regular days,Average orders
16,0,1,Chocolate Sandwich Cookies,61,19,5.8,23940,317121,1494,prior,...,5,8,10.0,12,1,both,Mid-range product,Regularly busy,Regular days,Average orders
17,0,1,Chocolate Sandwich Cookies,61,19,5.8,24740,200390,1540,prior,...,2,0,7.0,10,0,both,Mid-range product,Regularly busy,Regular days,Fewest orders
18,0,1,Chocolate Sandwich Cookies,61,19,5.8,24741,374436,1540,prior,...,1,21,6.0,9,1,both,Mid-range product,Regularly busy,Busiest days,Average orders
19,0,1,Chocolate Sandwich Cookies,61,19,5.8,24742,2920553,1540,prior,...,1,0,14.0,9,1,both,Mid-range product,Regularly busy,Busiest days,Fewest orders

# Create Loyalty Flag

In [28]:
# Question 4

In [29]:
#execute command to create column 'max_order' to establish number of orders per user

ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

In [30]:
ords_prods_merge.head(15)

,Unnamed: 0_x,product_id,product_name,aisle_id,department_id,prices,Unnamed: 0_y,order_id,user_id,eval_set,...,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order
0,0,1,Chocolate Sandwich Cookies,61,19,5.8,1987,3139998,138,prior,...,11,3.0,5,0,both,Mid-range product,Regularly busy,Regular days,Most orders,32
1,0,1,Chocolate Sandwich Cookies,61,19,5.8,1989,1977647,138,prior,...,17,20.0,1,1,both,Mid-range product,Regularly busy,Regular days,Average orders,32
2,0,1,Chocolate Sandwich Cookies,61,19,5.8,11433,389851,709,prior,...,21,6.0,20,0,both,Mid-range product,Busiest day,Busiest days,Average orders,5
3,0,1,Chocolate Sandwich Cookies,61,19,5.8,12198,652770,764,prior,...,13,21.0,10,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,3
4,0,1,Chocolate Sandwich Cookies,61,19,5.8,12200,1813452,764,prior,...,17,9.0,11,1,both,Mid-range product,Least busy,Slowest days,Average orders,3
5,0,1,Chocolate Sandwich Cookies,61,19,5.8,12372,1701441,777,prior,...,7,26.0,7,0,both,Mid-range product,Regularly busy,Busiest days,Average orders,26
6,0,1,Chocolate Sandwich Cookies,61,19,5.8,13096,1871483,825,prior,...,14,30.0,2,0,both,Mid-range product,Regularly busy,Regular days,Most orders,9
7,0,1,Chocolate Sandwich Cookies,61,19,5.8,14603,1290456,910,prior,...,10,30.0,1,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,12
8,0,1,Chocolate Sandwich Cookies,61,19,5.8,17065,369558,1052,prior,...,20,19.0,1,0,both,Mid-range product,Regularly busy,Busiest days,Average orders,20
9,0,1,Chocolate Sandwich Cookies,61,19,5.8,17070,589712,1052,prior,...,12,15.0,2,1,both,Mid-range product,Regularly busy,Busiest days,Most orders,20
10,0,1,Chocolate Sandwich Cookies,61,19,5.8,22082,1798115,1379,prior,...,11,21.0,1,0,both,Mid-range product,Regularly busy,Regular days,Most orders,10
11,0,1,Chocolate Sandwich Cookies,61,19,5.8,23713,497193,1480,prior,...,13,7.0,1,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,43
12,0,1,Chocolate Sandwich Cookies,61,19,5.8,23715,1727826,1480,prior,...,13,7.0,3,1,both,Mid-range product,Least busy,Slowest days,Most orders,43
13,0,1,Chocolate Sandwich Cookies,61,19,5.8,23716,2694698,1480,prior,...,12,12.0,4,1,both,Mid-range product,Regularly busy,Regular days,Most orders,43
14,0,1,Chocolate Sandwich Cookies,61,19,5.8,23937,3171753,1494,prior,...,10,2.0,8,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,13

In [31]:
#Define Loyalty Criteria

In [32]:
ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [33]:
ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [35]:
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [36]:
# Test the distribution of newly created category

In [37]:
ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: loyalty_flag, dtype: int64

In [45]:
# have a look to see if the max_order values match up with the loyalty_flag criteria...

ords_prods_merge[['user_id', 'loyalty_flag', 'max_order']].head(60)

    user_id      loyalty_flag  max_order
0       138  Regular customer         32
1       138  Regular customer         32
2       709      New customer          5
3       764      New customer          3
4       764      New customer          3
5       777  Regular customer         26
6       825      New customer          9
7       910  Regular customer         12
8      1052  Regular customer         20
9      1052  Regular customer         20
10     1379      New customer         10
11     1480    Loyal customer         43
12     1480    Loyal customer         43
13     1480    Loyal customer         43
14     1494  Regular customer         13
15     1494  Regular customer         13
16     1494  Regular customer         13
17     1540  Regular customer         28
18     1540  Regular customer         28
19     1540  Regular customer         28
20     1540  Regular customer         28
21     1540  Regular customer         28
22     1540  Regular customer         28
23     1540  Regular customer         28
24     1540  Regular customer         28
25     1540  Regular customer         28
26     1540  Regular customer         28
27     1540  Regular customer         28
28     1540  Regular customer         28
29     1540  Regular customer         28
30     1540  Regular customer         28
31     1540  Regular customer         28
32     1540  Regular customer         28
33     1540  Regular customer         28
34     1598      New customer          4
35     1598      New customer          4
36     1598      New customer          4
37     1647      New customer         10
38     1647      New customer         10
39     1647      New customer         10
40     1647      New customer         10
41     1647      New customer         10
42     2833      New customer         10
43     2850  Regular customer         23
44     2857  Regular customer         25
45     3010  Regular customer         13
46     3029      New customer          5
47     3395      New customer          6
48     3904      New customer          3
49     4006    Loyal customer         42
50     4006    Loyal customer         42
51     4006    Loyal customer         42
52     4006    Loyal customer         42
53     4006    Loyal customer         42
54     4122  Regular customer         40
55     4141      New customer          9
56     4343      New customer          4
57     4553      New customer          4
58     4845  Regular customer         14
59     6866      New customer          6

In [46]:
# Question 5

# Using the new categories of loyalty_flag, I aggregated by the 'prices' column

In [38]:
ords_prods_merge.groupby('loyalty_flag').agg({'prices': ['mean', 'min', 'max']})

                     prices
                       mean  min      max
loyalty_flag
Loyal customer    10.386336  1.0  99999.0
New customer      13.294670  1.0  99999.0
Regular customer  12.495717  1.0  99999.0

In [39]:
# The mean value is quite interesting. 
# The loyal customers spend the least in terms of the average cost per unit and the new customers spend the most. 
# My initial assumption was the opposite

In [40]:
# Question 6

# create low and high spender categories where the average price per item is <10 or >= 10 respectively

In [41]:
# Creating “average_price” column using transform()

ords_prods_merge['average_price'] = ords_prods_merge.groupby(['user_id'])['prices'].transform(np.mean)

In [42]:
ords_prods_merge.head()

,Unnamed: 0_x,product_id,product_name,aisle_id,department_id,prices,Unnamed: 0_y,order_id,user_id,eval_set,...,add_to_cart_order,reordered,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag,average_price
0,0,1,Chocolate Sandwich Cookies,61,19,5.8,1987,3139998,138,prior,...,5,0,both,Mid-range product,Regularly busy,Regular days,Most orders,32,Regular customer,6.935811
1,0,1,Chocolate Sandwich Cookies,61,19,5.8,1989,1977647,138,prior,...,1,1,both,Mid-range product,Regularly busy,Regular days,Average orders,32,Regular customer,6.935811
2,0,1,Chocolate Sandwich Cookies,61,19,5.8,11433,389851,709,prior,...,20,0,both,Mid-range product,Busiest day,Busiest days,Average orders,5,New customer,7.930208
3,0,1,Chocolate Sandwich Cookies,61,19,5.8,12198,652770,764,prior,...,10,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,3,New customer,4.972414
4,0,1,Chocolate Sandwich Cookies,61,19,5.8,12200,1813452,764,prior,...,11,1,both,Mid-range product,Least busy,Slowest days,Average orders,3,New customer,4.972414

In [43]:
# Creating a 'spending_flag' flag (Low spender)

ords_prods_merge.loc[ords_prods_merge['average_price'] < 10, 'spending_flag'] = 'Low spender'

In [44]:
# Creating a 'spending_flag' flag (High spender)

ords_prods_merge.loc[ords_prods_merge['average_price'] >= 10, 'spending_flag'] = 'High spender'

In [45]:
# Check the column and the flag are displayed correctly:

ords_prods_merge.tail(50)

,Unnamed: 0_x,product_id,product_name,aisle_id,department_id,prices,Unnamed: 0_y,order_id,user_id,eval_set,...,reordered,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag,average_price,spending_flag
32404809,49692,49688,Fresh Foaming Cleanser,73,11,13.5,1858123,2732438,111542,prior,...,0,both,Mid-range product,Busiest day,Busiest days,Average orders,29,Regular customer,7.615238,Low spender
32404810,49692,49688,Fresh Foaming Cleanser,73,11,13.5,1914787,2996443,114963,prior,...,0,both,Mid-range product,Regularly busy,Busiest days,Most orders,45,Loyal customer,397.793370,High spender
32404811,49692,49688,Fresh Foaming Cleanser,73,11,13.5,1979569,891179,118871,prior,...,0,both,Mid-range product,Regularly busy,Busiest days,Most orders,35,Regular customer,7.241190,Low spender
32404812,49692,49688,Fresh Foaming Cleanser,73,11,13.5,2025050,3290206,121646,prior,...,0,both,Mid-range product,Busiest day,Busiest days,Most orders,11,Regular customer,10.022764,High spender
32404813,49692,49688,Fresh Foaming Cleanser,73,11,13.5,2077777,2951582,124944,prior,...,0,both,Mid-range product,Busiest day,Busiest days,Most orders,6,New customer,8.400000,Low spender
32404814,49692,49688,Fresh Foaming Cleanser,73,11,13.5,2130787,328141,128148,prior,...,0,both,Mid-range product,Busiest day,Busiest days,Most orders,33,Regular customer,7.705316,Low spender
32404815,49692,49688,Fresh Foaming Cleanser,73,11,13.5,2130812,3041952,128148,prior,...,1,both,Mid-range product,Busiest day,Busiest days,Most orders,33,Regular customer,7.705316,Low spender
32404816,49692,49688,Fresh Foaming Cleanser,73,11,13.5,2143473,1897157,128930,prior,...,0,both,Mid-range product,Busiest day,Busiest days,Most orders,11,Regular customer,7.524390,Low spender
32404817,49692,49688,Fresh Foaming Cleanser,73,11,13.5,2143475,2476113,128930,prior,...,1,both,Mid-range product,Regularly busy,Regular days,Most orders,11,Regular customer,7.524390,Low spender
32404818,49692,49688,Fresh Foaming Cleanser,73,11,13.5,2159515,1631554,129901,prior,...,0,both,Mid-range product,Regularly busy,Regular days,Most orders,4,New customer,8.694872,Low spender
32404819,49692,49688,Fresh Foaming Cleanser,73,11,13.5,2369602,641382,142639,prior,...,0,both,Mid-range product,Regularly busy,Regular days,Most orders,27,Regular customer,9.872881,Low spender
32404820,49692,49688,Fresh Foaming Cleanser,73,11,13.5,2407810,253490,144914,prior,...,0,both,Mid-range product,Regularly busy,Busiest days,Average orders,28,Regular customer,8.062232,Low spender
32404821,49692,49688,Fresh Foaming Cleanser,73,11,13.5,2411509,965803,145111,prior,...,0,both,Mid-range product,Regularly busy,Slowest days,Average orders,16,Regular customer,8.177328,Low spender
32404822,49692,49688,Fresh Foaming Cleanser,73,11,13.5,2418435,393166,145526,prior,...,0,both,Mid-range product,Regularly busy,Busiest days,Most orders,23,Regular customer,76.089009,High spender
32404823,49692,49688,Fresh Foaming Cleanser,73,11,13.5,2422187,3058519,145732,prior,...,0,both,Mid-range product,Busiest day,Busiest days,Average orders,8,New customer,7.681667,Low spender
32404824,49692,49688,Fresh Foaming Cleanser,73,11,13.5,2431690,3122003,146323,prior,...,0,both,Mid-range product,Regularly busy,Busiest days,Most orders,9,New customer,8.740690,Low spender
32404825,49692,49688,Fresh Foaming Cleanser,73,11,13.5,2525055,2779979,151977,prior,...,0,both,Mid-range product,Busiest day,Busiest days,Most orders,8,New customer,8.110390,Low spender
32404826,49692,49688,Fresh Foaming Cleanser,73,11,13.5,2552939,2363598,153612,prior,...,0,both,Mid-range product,Regularly busy,Regular days,Most orders,5,New customer,9.400000,Low spender
32404827,49692,49688,Fresh Foaming Cleanser,73,11,13.5,2622480,967902,157883,prior,...,0,both,Mid-range product,Busiest day,Busiest days,Average orders,3,New customer,7.450000,Low spender
32404828,49692,49688,Fresh Foaming Cleanser,73,11,13.5,2642619,2932449,159099,prior,...,0,both,Mid-range product,Regularly busy,Regular days,Most orders,9,New customer,7.663559,Low spender
32404829,49692,49688,Fresh Foaming Cleanser,73,11,13.5,2649201,2744037,159487,prior,...,0,both,Mid-range product,Regularly busy,Regular days,Average orders,14,Regular customer,9.092424,Low spender
32404830,49692,49688,Fresh Foaming Cleanser,73,11,13.5,2649208,13797,159487,prior,...,1,both,Mid-range product,Busiest day,Busiest days,Most orders,14,Regular customer,9.092424,Low spender
32404831,49692,49688,Fresh Foaming Cleanser,73,11,13.5,2649211,258779,159487,prior,...,1,both,Mid-range product,Regularly busy,Regular days,Average orders,14,Regular customer,9.092424,Low spender
32404832,49692,49688,Fresh Foaming Cleanser,73,11,13.5,2649213,311401,159487,prior,...,1,both,Mid-range product,Least busy,Slowest days,Average orders,14,Regular customer,9.092424,Low spender
32404833,49692,49688,Fresh Foaming Cleanser,73,11,13.5,2651909,425916,159638,prior,...,0,both,Mid-range product,Regularly busy,Regular days,Most orders,7,New customer,7.869811,Low spender
32404834,49692,49688,Fresh Foaming Cleanser,73,11,13.5,2716531,2530161,163632,prior,...,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,8,New customer,8.890000,Low spender
32404835,49692,49688,Fresh Foaming Cleanser,73,11,13.5,2716533,1288677,163632,prior,...,1,both,Mid-range product,Regularly busy,Busiest days,Average orders,8,New customer,8.890000,Low spender
32404836,49692,49688,Fresh Foaming Cleanser,73,11,13.5,2729493,3008450,164453,prior,...,0,both,Mid-range product,Busiest day,Busiest days,Most orders,24,Regular customer,7.287013,Low spender
32404837,49692,49688,Fresh Foaming Cleanser,73,11,13.5,2754992,151501,166038,prior,...,0,both,Mid-range product,Regularly busy,Regular days,Most orders,15,Regular customer,7.612409,Low spender
32404838,49692,49688,Fresh Foaming Cleanser,73,11,13.5,2754997,2439935,166038,prior,...,1,both,Mid-range product,Least busy,Slowest days,Average orders,15,Regular customer,7.612409,Low spender
32404839,49692,49688,Fresh Foaming Cleanser,73,11,13.5,2757790,1400940,166213,prior,...,0,both,Mid-range product,Regularly busy,Busiest days,Average orders,3,New customer,7.473913,Low spender
32404840,49692,49688,Fresh Foaming Cleanser,73,11,13.5,2846453,1219750,171743,prior,...,0,both,Mid-range product,Busiest day,Busiest days,Average orders,10,New customer,6.991949,Low spender
32404841,49692,49688,Fresh Foaming Cleanser,73,11,13.5,2854931,307087,172262,prior,...,0,both,Mid-range product,Regularly busy,Regular days,Most orders,4,New customer,8.036585,Low spender
32404842,49692,49688,Fresh Foaming Cleanser,73,11,13.5,2932929,2454083,176942,prior,...,0,both,Mid-range product,Regularly busy,Regular days,Average orders,4,New customer,7.831250,Low spender
32404843,49692,49688,Fresh Foaming Cleanser,73,11,13.5,2960831,2710528,178693,prior,...,0,both,Mid-range product,Regularly busy,Regular days,Most orders,60,Loyal customer,8.360085,Low spender
32404844,49692,49688,Fresh Foaming Cleanser,73,11,13.5,2961760,1173882,178752,prior,...,0,both,Mid-range product,Busiest day,Busiest days,Fewest orders,16,Regular customer,8.643223,Low spender
32404845,49692,49688,Fresh Foaming Cleanser,73,11,13.5,2961768,1525694,178752,prior,...,1,both,Mid-range product,Regularly busy,Regular days,Most orders,16,Regular customer,8.643223,Low spender
32404846,49692,49688,Fresh Foaming Cleanser,73,11,13.5,3032345,2439069,182948,prior,...,0,both,Mid-range product,Regularly busy,Regular days,Most orders,8,New customer,7.306667,Low spender
32404847,49692,49688,Fresh Foaming Cleanser,73,11,13.5,3032349,2392655,182948,prior,...,1,both,Mid-range product,Regularly busy,Regular days,Most orders,8,New customer,7.306667,Low spender
32404848,49692,49688,Fresh Foaming Cleanser,73,11,13.5,3042436,848810,183548,prior,...,0,both,Mid-range product,Regularly busy,Regular days,Most orders,15,Regular customer,8.340659,Low spender
32404849,49692,49688,Fresh Foaming Cleanser,73,11,13.5,3051947,2251059,184081,prior,...,0,both,Mid-range product,Regularly busy,Regular days,Most orders,11,Regular customer,7.684426,Low spender
32404850,49692,49688,Fresh Foaming Cleanser,73,11,13.5,3109393,846716,187523,prior,...,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,17,Regular customer,7.812676,Low spender
32404851,49692,49688,Fresh Foaming Cleanser,73,11,13.5,3119459,362546,188073,prior,...,0,both,Mid-range product,Regularly busy,Regular days,Fewest orders,31,Regular customer,6.058416,Low spender
32404852,49692,49688,Fresh Foaming Cleanser,73,11,13.5,3119461,3166828,188073,prior,...,1,both,Mid-range product,Regularly busy,Busiest days,Most orders,31,Regular customer,6.058416,Low spender
32404853,49692,49688,Fresh Foaming Cleanser,73,11,13.5,3274661,3106363,197371,prior,...,0,both,Mid-range product,Least busy,Slowest days,Most orders,10,New customer,8.814508,Low spender
32404854,49692,49688,Fresh Foaming Cleanser,73,11,13.5,3321928,1788356,200215,prior,...,0,both,Mid-range product,Busiest day,Busiest days,Most orders,6,New customer,8.220313,Low spender
32404855,49692,49688,Fresh Foaming Cleanser,73,11,13.5,3324686,3401313,200377,prior,...,0,both,Mid-range product,Least busy,Slowest days,Most orders,4,New customer,7.364516,Low spender
32404856,49692,49688,Fresh Foaming Cleanser,73,11,13.5,3332310,809510,200873,prior,...,0,both,Mid-range product,Regularly busy,Slowest days,Average orders,20,Regular customer,8.500344,Low spender
32404857,49692,49688,Fresh Foaming Cleanser,73,11,13.5,3332314,2359893,200873,prior,...,1,both,Mid-range product,Regularly busy,Slowest days,Most orders,20,Regular customer,8.500344,Low spender
32404858,49692,49688,Fresh Foaming Cleanser,73,11,13.5,3416620,2385091,205926,prior,...,0,both,Mid-range product,Regularly busy,Busiest days,Most orders,11,Regular customer,8.133333,Low spender

In [46]:
# Check the frequency

ords_prods_merge['spending_flag'].value_counts(dropna = False)

Low spender     31770614
High spender      634245
Name: spending_flag, dtype: int64

In [47]:
# Question 7

# Classify 'frequent' and 'non-frequent' customers
# Use each customer's median of 'days_since_prior_order' column to define
# >20 'Non frequent customer'
# >10, <=20 'Regular customer'
# <=10 'Frequent customer'

In [48]:
ords_prods_merge.head(15)

,Unnamed: 0_x,product_id,product_name,aisle_id,department_id,prices,Unnamed: 0_y,order_id,user_id,eval_set,...,reordered,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag,average_price,spending_flag
0,0,1,Chocolate Sandwich Cookies,61,19,5.8,1987,3139998,138,prior,...,0,both,Mid-range product,Regularly busy,Regular days,Most orders,32,Regular customer,6.935811,Low spender
1,0,1,Chocolate Sandwich Cookies,61,19,5.8,1989,1977647,138,prior,...,1,both,Mid-range product,Regularly busy,Regular days,Average orders,32,Regular customer,6.935811,Low spender
2,0,1,Chocolate Sandwich Cookies,61,19,5.8,11433,389851,709,prior,...,0,both,Mid-range product,Busiest day,Busiest days,Average orders,5,New customer,7.930208,Low spender
3,0,1,Chocolate Sandwich Cookies,61,19,5.8,12198,652770,764,prior,...,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,3,New customer,4.972414,Low spender
4,0,1,Chocolate Sandwich Cookies,61,19,5.8,12200,1813452,764,prior,...,1,both,Mid-range product,Least busy,Slowest days,Average orders,3,New customer,4.972414,Low spender
5,0,1,Chocolate Sandwich Cookies,61,19,5.8,12372,1701441,777,prior,...,0,both,Mid-range product,Regularly busy,Busiest days,Average orders,26,Regular customer,6.935398,Low spender
6,0,1,Chocolate Sandwich Cookies,61,19,5.8,13096,1871483,825,prior,...,0,both,Mid-range product,Regularly busy,Regular days,Most orders,9,New customer,5.957576,Low spender
7,0,1,Chocolate Sandwich Cookies,61,19,5.8,14603,1290456,910,prior,...,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,12,Regular customer,6.680000,Low spender
8,0,1,Chocolate Sandwich Cookies,61,19,5.8,17065,369558,1052,prior,...,0,both,Mid-range product,Regularly busy,Busiest days,Average orders,20,Regular customer,7.162500,Low spender
9,0,1,Chocolate Sandwich Cookies,61,19,5.8,17070,589712,1052,prior,...,1,both,Mid-range product,Regularly busy,Busiest days,Most orders,20,Regular customer,7.162500,Low spender
10,0,1,Chocolate Sandwich Cookies,61,19,5.8,22082,1798115,1379,prior,...,0,both,Mid-range product,Regularly busy,Regular days,Most orders,10,New customer,5.813636,Low spender
11,0,1,Chocolate Sandwich Cookies,61,19,5.8,23713,497193,1480,prior,...,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,43,Loyal customer,5.081633,Low spender
12,0,1,Chocolate Sandwich Cookies,61,19,5.8,23715,1727826,1480,prior,...,1,both,Mid-range product,Least busy,Slowest days,Most orders,43,Loyal customer,5.081633,Low spender
13,0,1,Chocolate Sandwich Cookies,61,19,5.8,23716,2694698,1480,prior,...,1,both,Mid-range product,Regularly busy,Regular days,Most orders,43,Loyal customer,5.081633,Low spender
14,0,1,Chocolate Sandwich Cookies,61,19,5.8,23937,3171753,1494,prior,...,0,both,Mid-range product,Regularly busy,Slowest days,Most orders,13,Regular customer,6.803797,Low spender

In [49]:
# Creating “median_prior_orders” column using transform()

ords_prods_merge['median_prior_orders'] = ords_prods_merge.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

In [50]:
ords_prods_merge.head()

,Unnamed: 0_x,product_id,product_name,aisle_id,department_id,prices,Unnamed: 0_y,order_id,user_id,eval_set,...,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag,average_price,spending_flag,median_prior_orders
0,0,1,Chocolate Sandwich Cookies,61,19,5.8,1987,3139998,138,prior,...,both,Mid-range product,Regularly busy,Regular days,Most orders,32,Regular customer,6.935811,Low spender,8.0
1,0,1,Chocolate Sandwich Cookies,61,19,5.8,1989,1977647,138,prior,...,both,Mid-range product,Regularly busy,Regular days,Average orders,32,Regular customer,6.935811,Low spender,8.0
2,0,1,Chocolate Sandwich Cookies,61,19,5.8,11433,389851,709,prior,...,both,Mid-range product,Busiest day,Busiest days,Average orders,5,New customer,7.930208,Low spender,8.0
3,0,1,Chocolate Sandwich Cookies,61,19,5.8,12198,652770,764,prior,...,both,Mid-range product,Regularly busy,Slowest days,Most orders,3,New customer,4.972414,Low spender,13.0
4,0,1,Chocolate Sandwich Cookies,61,19,5.8,12200,1813452,764,prior,...,both,Mid-range product,Least busy,Slowest days,Average orders,3,New customer,4.972414,Low spender,13.0

In [51]:
# Creating a 'order_frequency_flag' flag

ords_prods_merge.loc[ords_prods_merge['median_prior_orders'] > 20, 'order_frequency_flag'] = 'Non-frequent customer'

In [52]:
# Creating a 'order_frequency_flag' flag

ords_prods_merge.loc[(ords_prods_merge['median_prior_orders'] > 10) & (ords_prods_merge['median_prior_orders'] <= 20), 'order_frequency_flag'] = 'Regular customer'

In [53]:
# Creating a 'order_frequency_flag' flag

ords_prods_merge.loc[ords_prods_merge['median_prior_orders'] <= 10, 'order_frequency_flag'] = 'Frequent customer'

In [54]:
ords_prods_merge.head()

,Unnamed: 0_x,product_id,product_name,aisle_id,department_id,prices,Unnamed: 0_y,order_id,user_id,eval_set,...,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag,average_price,spending_flag,median_prior_orders,order_frequency_flag
0,0,1,Chocolate Sandwich Cookies,61,19,5.8,1987,3139998,138,prior,...,Mid-range product,Regularly busy,Regular days,Most orders,32,Regular customer,6.935811,Low spender,8.0,Frequent customer
1,0,1,Chocolate Sandwich Cookies,61,19,5.8,1989,1977647,138,prior,...,Mid-range product,Regularly busy,Regular days,Average orders,32,Regular customer,6.935811,Low spender,8.0,Frequent customer
2,0,1,Chocolate Sandwich Cookies,61,19,5.8,11433,389851,709,prior,...,Mid-range product,Busiest day,Busiest days,Average orders,5,New customer,7.930208,Low spender,8.0,Frequent customer
3,0,1,Chocolate Sandwich Cookies,61,19,5.8,12198,652770,764,prior,...,Mid-range product,Regularly busy,Slowest days,Most orders,3,New customer,4.972414,Low spender,13.0,Regular customer
4,0,1,Chocolate Sandwich Cookies,61,19,5.8,12200,1813452,764,prior,...,Mid-range product,Least busy,Slowest days,Average orders,3,New customer,4.972414,Low spender,13.0,Regular customer

In [55]:
# Check the frequency

ords_prods_merge['order_frequency_flag'].value_counts(dropna = False)

Frequent customer        20514478
Regular customer          7307135
Non-frequent customer     4583246
Name: order_frequency_flag, dtype: int64

In [56]:
# Check the null values

print('Records in df_orders_products_merged with null values in column order_frequency_flag:')
ords_prods_merge[ords_prods_merge['order_frequency_flag'].isnull()][['user_id', 'days_since_prior_order', 'median_prior_orders', 'order_frequency_flag']]

Records in df_orders_products_merged with null values in column order_frequency_flag:

Empty DataFrame
Columns: [user_id, days_since_prior_order, median_prior_orders, order_frequency_flag]
Index: []

#No null values since I replaced the '1st Order entries' in the 'days_since_prior_order' column

In [58]:
ords_prods_merge.to_pickle(os.path.join(path, '2 Data','Prepared Data', 'orders_products_merged_updated_4.8_revised.pkl'))

In [57]:
ords_prods_merge.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 32404859 entries, 0 to 32404858
Data columns (total 27 columns):
 #   Column                  Dtype
---  ------                  -----
 0   Unnamed: 0_x            int64
 1   product_id              int64
 2   product_name            object
 3   aisle_id                int64
 4   department_id           int64
 5   prices                  float64
 6   Unnamed: 0_y            int64
 7   order_id                int64
 8   user_id                 int64
 9   eval_set                object
 10  order_number            int64
 11  order_dow               int64
 12  order_hour_of_day       int64
 13  days_since_prior_order  object
 14  add_to_cart_order       int64
 15  reordered               int64
 16  _merge                  category
 17  price_range_loc         object
 18  busiest_day             object
 19  busiest_days            object
 20  busiest_period_of_day   object
 21  max_order               int64
 22  loyalty_flag            object
 23  average_price           float64
 24  spending_flag           object
 25  median_prior_orders     float64
 26  order_frequency_flag    object
dtypes: category(1), float64(3), int64(13), object(10)
memory usage: 6.5+ GB